### PR TITLE
issues-194 : Initial docker development environment image and docs

### PR DESCRIPTION
**Pull request by ud3sh**
Original Draft PR from [@aaronsteers](https://github.com/aaronsteers) https://github.com/evidence-dev/evidence/pull/230
Big thanks to AJ for the idea and the suggestions in the draft PR.  The README describes the background and how this works.

I pushed a locally build version of the image here -> https://hub.docker.com/repository/docker/evidencedev/devenv 
The image is about 200MB uncompressed (about 50MB compressed). Hence, the docs in the README.md should work as described as is.  Any subsequent pushes to main should trigger a github action to update the image.

### CODE REVIEW

**Comment by aaronsteers** [comment]
Exciting! 🎉

**Comment by ud3sh** [comment]
Still pending related items that I can think of:
* once things have been finalized, add a section from the main docs (Docusaur) section on developing using Docker dev environment. There will likely to be quite a bit of overlap with the ReadMe file.
* share Dockerhub details with team.

Longer Term:
* We should consider setting up cert so that the namespace for the container tag will start with evidence.dev/* instead of evidencedev (though many official OSS images don't bother with it).
* Make it easier to change the default port -etc (perhaps using options)

**Comment by mcrascal** [comment]
Hey Udesh, this is super exciting. 

I am a docker noob, so this might be something I'm doing wrong, but I get stuck running through `Option 2: Creating a new evidence project from scratch using the Evidence project template` 

1. The project init's successfully and populates the directory 
2. When it goes to run the dev server, the terminal show's `SvelteKit v1.0.0-next.202` but it doesn't display localhost:3000 as expected
3. localhost:3000 doesn't respond
4. I can't kill the process in the terminal with `ctrl-c`

**Comment by ud3sh** [comment]
> Hey @ud3sh, this is super exciting.
> 
> I am a docker noob, so this might be something I'm doing wrong, but I get stuck running through `Option 2: Creating a new evidence project from scratch using the Evidence project template`
> 
> 1. The project init's successfully and populates the directory
> 2. When it goes to run the dev server, the terminal show's `SvelteKit v1.0.0-next.202` but it doesn't display localhost:3000 as expected
> 3. localhost:3000 doesn't respond
> 4. I can't kill the process in the terminal with `ctrl-c`

Thanks for testing this out @mcrascal. In my case, I also don't see the `localhost:3000` in your step 2), but `localhost:3000` does work for me in your step 3) and it's definitely the contents of the new project that was created.

My suspicions:
-Docker is known to has some runtime issues on Apple Silicon .  `Ctrl +C` issue makes me think this is more likely it  (there are workarounds, that I'll have to dig into - I just happen to be on an x86 mac).
-I made a general security-like configuration change in my in the past that makes it easier to work containers.

We can do some live debugging if you do have some time, if it happens to be one of the above.  But before we do that, can. you provide me with the following to narrow down few things:

1)If you've already tried it, did Option 1 work for you?

2)Can you see how much resources your Docker Desktop is allocation in terms of CPU and memory.  It's in the Docker Desktop Setting Tabs under Preferences/Resources => https://docs.docker.com/desktop/mac/ .  Bonus if you can re-run it with higher settings. Anecdotally, I've heard this fixed a bunch of issues on M1 machines. Having said that my container instance isn't using more than 200MB of RAM.

3)Can you send me the logs on your terminal when you run the option?

4)If your container is still running, can you run `lsof -i :3000 | grep LISTEN` ?

**Comment by mcrascal** [comment]
> 1)If you've already tried it, did Option 1 work for you? 
Just tried it, the project runs correctly with `npm run dev` but fails in the same way with `docker run [...]` 
> 2)Can you see how much resources your Docker Desktop is allocation in terms of CPU and memory.
Loads: 8GB ram, 5 CPUs 
> 3)Can you send me the logs on your terminal when you run the option?
> 4)If your container is still running, can you run lsof -i :3000 | grep LISTEN ?
Sent in a dm

**Pull request merged**
